version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=nest-tempalte
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
  nest-template:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=8080
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DBUSER=postgres
      - DBHOST=postgres
      - DBNAME=postgres
      - DBPASSWORD=postgres_password
      - DBPORT=5432
      - SECRET_KEY=IMBATMAN
      - NODE_ENV=development
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
